// Parameter definitions derived from astromugs dataclasses.
// Each entry mirrors a field() from the Python source of truth.

// ---------- struct.py ----------

export const diskFields = [
  { name: 'rin',            type: 'float', default: 1.0,       desc: '[AU] Inner radius' },
  { name: 'rout',           type: 'float', default: 300,       desc: '[AU] Outer radius' },
  { name: 'ref_radius',     type: 'float', default: 100,       desc: '[AU] Reference radius for parametric laws' },
  { name: 'p_exp',          type: 'float', default: 1.5,       desc: 'Surface density exponent' },
  { name: 'sigma_gas_ref',  type: 'float', default: 0.335,     desc: '[g.cm-2] Surface density of the gas at reference radius' },
  { name: 'sigma_compute',  type: 'str',   default: 'model',   desc: 'Model or custom surface density profile', options: ['model', 'custom'] },
  { name: 'sigma_path',     type: 'str',   default: null,      desc: 'Path to file for custom surface densities (if sigma_compute=custom)' },
  { name: 'h0',             type: 'float', default: 10,        desc: '[AU] Scale height at reference radius' },
  { name: 'q_exp',          type: 'float', default: 0.4,       desc: 'Exponent for the radial variation of temperature and gas scale height' },
  { name: 'tmidplan_ref',   type: 'float', default: 10,        desc: '[K] Midplane temperature at the reference radius' },
  { name: 'tatmos_ref',     type: 'float', default: 50,        desc: '[K] Atmospheric temperature at the reference radius (where z=n*H)' },
  { name: 'sigma_t',        type: 'float', default: 2.0,       desc: 'Stiffness of the vertical temperature profile' },
  { name: 'max_H',          type: 'float', default: 4.0,       desc: 'Maximum altitude in fraction of scale height' },
  { name: 'isothermal',     type: 'bool',  default: false,     desc: 'Is vertically isothermal. Default is non-isothermal' },
  { name: 'disk_mass',      type: 'float', default: 0.15,      desc: '[Msun] Total mass of the disk' },
  { name: 'dust_mass',      type: 'float', default: 1e-4,      desc: '[Msun] Total dust mass in the disk' },
  { name: 'dtogas',         type: 'float', default: 0.01,      desc: 'Dust to gas mass ratio' },
  { name: 'd_exp',          type: 'float', default: 3.5,       desc: "Size distribution exponent" },
  { name: 'rho_m',          type: 'float', default: 3.0,       desc: '[g.cm-3] Material density of the grains' },
  { name: 'settling',       type: 'bool',  default: true,      desc: 'Enable vertical settling' },
  { name: 'settfact',       type: 'float', default: 0.9,       desc: 'Settling factor' },
  { name: 'schmidtnumber',  type: 'float', default: 1.0,       desc: 'Schmidt number' },
  { name: 'q_c',            type: 'float', default: 6.0,       desc: 'Extinction efficiency at resonance' },
  { name: 'acc_rate',       type: 'float', default: 1e-5,      desc: '[Msun yr-1] Accretion rate' },
  { name: 'alpha',          type: 'float', default: 0.01,      desc: 'Viscosity coefficient' },
  { name: 'lim_h',          type: 'float', default: 1.0,       desc: 'Fraction of scale height until which accretion heating is computed' },
  { name: 'star_mass',      type: 'float', default: 0.58,      desc: '[Msun] Mass of the central star' },
  { name: 'nz_chem',        type: 'int',   default: 50,        desc: 'Number of vertical spatial points for chemistry' },
]

export const envelopeFields = [
  { name: 'rmin',           type: 'float', default: 1.0,       desc: '[AU] Inner radius of the envelope' },
  { name: 'rmax',           type: 'float', default: 5000,      desc: '[AU] Outer radius of the envelope' },
  { name: 'r_centri',       type: 'float', default: 100,       desc: '[AU] Centrifugal radius (where envelope flattens)' },
  { name: 'acc_rate',       type: 'float', default: 1e-5,      desc: '[Msun yr-1] Accretion rate' },
  { name: 'dtogas',         type: 'float', default: 0.01,      desc: 'Dust to gas mass ratio' },
  { name: 'dust_env_mass',  type: 'float', default: 1e-5,      desc: '[Msun] Total dust mass of the envelope' },
  { name: 'cavpl',          type: 'float', default: 1.0,       desc: 'Opening angle and shape of the outflow' },
  { name: 'cavz0',          type: 'float', default: 10,        desc: '[AU] Cavity reference height' },
  { name: 'cav_fact',       type: 'float', default: 10,        desc: 'Factor of decrease of the density in the cavity' },
  { name: 'coordsystem',    type: 'str',   default: 'spherical', desc: 'Coordinate system for radiative transfer', options: ['spherical', 'cylindrical'] },
]

// ---------- thermal.py ----------

export const starFields = [
  { name: 'mass',           type: 'float', default: 1,         desc: '[Msun] Stellar mass' },
  { name: 'temperature',    type: 'float', default: 4000,      desc: '[K] Stellar surface temperature' },
  { name: 'luminosity',     type: 'float', default: 4000,      desc: '[Lsun] Stellar luminosity' },
  { name: 'x',              type: 'float', default: 0,         desc: '[AU] Stellar position in x' },
  { name: 'y',              type: 'float', default: 0,         desc: '[AU] Stellar position in y' },
  { name: 'z',              type: 'float', default: 0,         desc: '[AU] Stellar position in z' },
]

export const controlFields = [
  { name: 'incl_dust',               type: 'float', default: null, desc: 'Include dust continuum emission (0=off, 1=on)' },
  { name: 'incl_lines',              type: 'float', default: null, desc: 'Include line emission (0=off, 1=on)' },
  { name: 'incl_freefree',           type: 'float', default: null, desc: 'Include free-free emission (0=off, 1=on)' },
  { name: 'nphot_therm',             type: 'float', default: null, desc: 'Number of photon packages for thermal Monte Carlo' },
  { name: 'nphot_scat',              type: 'float', default: null, desc: 'Number of photon packages for scattering Monte Carlo' },
  { name: 'nphot_mono',              type: 'float', default: null, desc: 'Number of photon packages for monochromatic Monte Carlo' },
  { name: 'nphot_spec',              type: 'float', default: null, desc: 'Number of photon packages for spectrum calculation' },
  { name: 'iseed',                   type: 'int',   default: null, desc: 'Random number generator seed' },
  { name: 'ifast',                   type: 'float', default: null, desc: 'Fast method for thermal emission (1=on)' },
  { name: 'enthres',                 type: 'float', default: null, desc: 'Energy threshold for thermal Monte Carlo convergence' },
  { name: 'itempdecoup',             type: 'int',   default: null, desc: 'Decouple temperatures of different dust species (1=on)' },
  { name: 'istar_sphere',            type: 'int',   default: null, desc: 'Treat stars as finite spheres (1=on)' },
  { name: 'ntemp',                   type: 'int',   default: null, desc: 'Number of temperature grid points for emissivity table' },
  { name: 'temp0',                   type: 'float', default: null, desc: '[K] Minimum temperature in emissivity table' },
  { name: 'temp1',                   type: 'float', default: null, desc: '[K] Maximum temperature in emissivity table' },
  { name: 'scattering_mode_max',     type: 'int',   default: null, desc: 'Max scattering mode (0=none, 1=iso, 2=aniso, 5=full polarization)' },
  { name: 'rto_style',               type: 'float', default: null, desc: 'Output format (1=ASCII, 2=F77 unformatted, 3=C binary)' },
  { name: 'camera_tracemode',        type: 'float', default: null, desc: 'Ray tracing mode (1=full, -1=emission only)' },
  { name: 'camera_nrrefine',         type: 'float', default: null, desc: 'Number of sub-pixel refinements for anti-aliasing' },
  { name: 'camera_refine_criterion', type: 'float', default: null, desc: 'Intensity contrast criterion for sub-pixel refinement' },
  { name: 'camera_incl_stars',       type: 'float', default: null, desc: 'Include stellar emission in images (1=on)' },
  { name: 'camera_starsphere_nrpix', type: 'float', default: null, desc: 'Number of pixels for stellar sphere rendering' },
  { name: 'camera_spher_cavity_relres', type: 'float', default: null, desc: 'Relative resolution for spherical cavity' },
  { name: 'camera_localobs_projection', type: 'float', default: null, desc: 'Projection type for local observer camera' },
  { name: 'camera_min_dangle',       type: 'float', default: null, desc: 'Minimum angle step for ray integration [rad]' },
  { name: 'camera_max_dangle',       type: 'float', default: null, desc: 'Maximum angle step for ray integration [rad]' },
  { name: 'camera_min_dr',           type: 'float', default: null, desc: 'Minimum spatial step for ray integration [cm]' },
  { name: 'camera_diagnostics_subpix', type: 'float', default: null, desc: 'Enable sub-pixel diagnostics output (1=on)' },
  { name: 'camera_secondorder',      type: 'float', default: null, desc: 'Second-order integration for ray tracing (1=on)' },
  { name: 'camera_interpol_jnu',     type: 'float', default: null, desc: 'Interpolate emissivity along camera rays (1=on)' },
  { name: 'camera_scatsrc_allfreq',  type: 'float', default: null, desc: 'Scattering source at all frequencies (1=on)' },
  { name: 'mc_weighted_photons',     type: 'float', default: null, desc: 'Use luminosity-weighted photon packages (1=on)' },
  { name: 'optimized_motion',        type: 'float', default: null, desc: 'Optimized photon propagation in thick regions (1=on)' },
  { name: 'lines_mode',              type: 'float', default: null, desc: 'Line transfer mode (1=LTE, 3=LVG/Sobolev, etc.)' },
  { name: 'lines_maxdoppler',        type: 'float', default: null, desc: 'Max Doppler shift in local line width units' },
  { name: 'lines_partition_ntempint', type: 'float', default: null, desc: 'Temperature intervals for partition function table' },
  { name: 'lines_partition_temp0',   type: 'float', default: null, desc: '[K] Min temperature for partition function table' },
  { name: 'lines_partition_temp1',   type: 'float', default: null, desc: '[K] Max temperature for partition function table' },
  { name: 'lines_show_pictograms',   type: 'float', default: null, desc: 'Show ASCII pictograms of line transitions (1=on)' },
  { name: 'tgas_eq_tdust',           type: 'int',   default: null, desc: 'Set gas temperature = dust temperature (1=on)' },
  { name: 'modified_random_walk',    type: 'float', default: null, desc: 'Enable Modified Random Walk for thick cells (1=on)' },
  { name: 'mrw_gamma',               type: 'float', default: null, desc: 'Gamma factor for MRW step size' },
  { name: 'mrw_tauthres',            type: 'float', default: null, desc: 'Optical depth threshold for MRW trigger' },
  { name: 'mrw_count_trigger',       type: 'float', default: null, desc: 'Photon count threshold for MRW trigger' },
  { name: 'setthreads',              type: 'float', default: null, desc: 'Number of OpenMP threads' },
  { name: 'mc_scat_maxtauabs',       type: 'float', default: null, desc: 'Max absorption optical depth per scattering step' },
  { name: 'writeimage_unformatted',  type: 'float', default: null, desc: 'Write image output in unformatted binary (1=on)' },
  { name: 'subbox_nx',               type: 'float', default: null, desc: 'Subbox cells in x-direction' },
  { name: 'subbox_ny',               type: 'float', default: null, desc: 'Subbox cells in y-direction' },
  { name: 'subbox_nz',               type: 'float', default: null, desc: 'Subbox cells in z-direction' },
  { name: 'subbox_x0',               type: 'float', default: null, desc: 'Subbox min x [cm]' },
  { name: 'subbox_x1',               type: 'float', default: null, desc: 'Subbox max x [cm]' },
  { name: 'subbox_y0',               type: 'float', default: null, desc: 'Subbox min y [cm]' },
  { name: 'subbox_y1',               type: 'float', default: null, desc: 'Subbox max y [cm]' },
  { name: 'subbox_z0',               type: 'float', default: null, desc: 'Subbox min z [cm]' },
  { name: 'subbox_z1',               type: 'float', default: null, desc: 'Subbox max z [cm]' },
]

export const waveFields = [
  { name: 'lmin',           type: 'float', default: 0.0912,    desc: '[micron] Minimum wavelength' },
  { name: 'lmax',           type: 'float', default: 10000,     desc: '[micron] Maximum wavelength' },
  { name: 'na',             type: 'int',   default: 200,       desc: 'Number of wavelengths' },
  { name: 'lmin_mono',      type: 'float', default: 0.0912,    desc: '[micron] Minimum monochromatic wavelength' },
  { name: 'lmax_mono',      type: 'float', default: 10000,     desc: '[micron] Maximum monochromatic wavelength' },
  { name: 'na_mono',        type: 'int',   default: 200,       desc: 'Number of monochromatic wavelengths' },
]

export const gridFields = [
  { name: 'nr',             type: 'int',   default: 101,       desc: 'Number of disk radii edges' },
  { name: 'ntheta',         type: 'int',   default: 181,       desc: 'Number of edge theta angles' },
  { name: 'nphi',           type: 'int',   default: 2,         desc: 'Number of phi angles' },
  { name: 'coordsystem',    type: 'str',   default: 'spherical', desc: 'Coordinate system for radiative transfer', options: ['spherical', 'cylindrical'] },
]
